---
- name: installing telnet on all nodes
  hosts: app
  tasks:
    - name: Installing telnet
      yum:
        name: telnet
        state: present

    - name: Print I LOVE LINUX on CLI
      debug: 
        msg: I LOVE LINUX
